version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 90:3000
    volumes:
      - /home/$USER/docker/09.grafana/grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana_data:
