version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - /mnt/usb_drive/jellyfin_movies:/media/movies
      - /home/$USER/docker/07.jellyfin/jellyfin_config:/config
      - /home/$USER/docker/07.jellyfin/jellyfin_cache:/cache
    restart: unless-stopped

volumes:
  jellyfin_config:
  jellyfin_cache:
